### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by a-rosenberg** [jrosen48/PISA-API#1]
I'm going to be at sea for ~20 days starting this weekend.  If theres a way for me to help develop on this, this would be a really good time to get a start on building the infrastructure -- even if we can't test full capability with full data volumes.  I will have enough internet for communicating with the repo, but likely not testing with live web transfers.

Perhaps we would save a sample data set to work with and build tests from?

Aaron

**Comment by jrosen48** [comment]
That sounds like a good plan. Unfortunately the data available through the
PISA website is only in SPSS and SAS proprietary formats, and I'm on the
road, so I'll have to share a Google Drive folder for now.

On Thu, Aug 10, 2017, 2:17 PM a-rosenberg <notifications@github.com> wrote:

> I'm going to be at sea for ~20 days starting this weekend. If theres a way
> for me to help develop on this, this would be a really good time to get a
> start on building the infrastructure -- even if we can't test full
> capability with full data volumes. I will have enough internet for
> communicating with the repo, but likely not testing with live web transfers.
>
> Perhaps we would save a sample data set to work with and build tests from?
>
> Aaron
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jrosen48_PISA-2DAPI_issues_1&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=K686QAY7eaZdPEFBr8PPgs7NJEd4IX1trEl5UE4sKWQ&m=gMZUDhBzn0kA3js6LHA0mfsshGx380-9XmNnuR5k97Q&s=N7c9o4Pm8kUFSk-hPEoDlmDesxsnW4xzJeXCZxWX4ps&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEYh9heSOCCIKHiUDc-5FILgOdk5hfmBdTks5sW0kqgaJpZM4Ozy01&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=K686QAY7eaZdPEFBr8PPgs7NJEd4IX1trEl5UE4sKWQ&m=gMZUDhBzn0kA3js6LHA0mfsshGx380-9XmNnuR5k97Q&s=vdiIY_OWkuTHc5jNT4Cf6BGFbjtk7Hi-nMbY7GT5ZWI&e=>
> .
>
-- 
Joshua Rosenberg, Ph.D. Candidate
Educational Psychology ​&​ Educational Technology
Michigan State University
https://urldefense.proofpoint.com/v2/url?u=http-3A__jmichaelrosenberg.com&d=DwIFaQ&c=nE__W8dFE-shTxStwXtp0A&r=Yced1TnnMllU5ofojLKiDPsnq37GU0yyMfEjC9rf5bOTqtnPJpNpUoCToSsVW7r_QBc_2l4X_bO6m2X_ViQKIDrA1xWFlBQsUlPj41s_PPj_o9JWiuTKft1Be3yBgUw87uq7JPEFWWGdZo5Dx1QEjA&m=h_9olqzmrSEOXkLqck2JzTaLPtBh4rJV2bqrSi9crFM&s=4m9de2h9J9aTBmWpixLZteVS0-088tvjT0Im46flB_w&e=
